### ISSUE TITLE
[FEATURE REQUEST] Add setup instructions 

### ISSUE THREAD

**Issue by darigovresearch** [ethcatherders/ech-website-v3#36]
Given that it's moved from vanilla html & js may be good to have instructions on how to run code locally to help with making pull requests for the repo in the readme

**Comment by darigovresearch** [comment]
Pull request https://github.com/ethcatherders/ech-website-v3/pull/37 should resolve this issue if merged

**Comment by geovgy** [comment]
Good suggestion. Merged.
